project:
  type: website
  output-dir: docs
  
website:
  title: "maryhen26.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MP1.qmd
      - Census_Data.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full



